# Generated by Django 3.1.7 on 2021-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200, null=True)),
                ('Sub_Type', models.CharField(max_length=100, null=True)),
                ('Description_of_your_issue', models.TextField(max_length=200, null=True)),
                ('Priority', models.CharField(max_length=200, null=True)),
                ('Attach_File', models.ImageField(null=True, upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raise_Ticket',
                'verbose_name_plural': 'Raise_Tickets',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
